### ISSUE TITLE
[BUG] Console errors

### ISSUE THREAD

**Issue by brunogcar** [alemelis/sd-webui-ar#1]
I've been following the pull request on A1111 SD and personally think it is a feature that should be on web ui, anyway thanks for creating an extension, but ...
```
Error calling: D:\GitHub\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-ar\scripts\sd-webui-ar.py/ui
Traceback (most recent call last):
  File "D:\GitHub\AUTOMATIC1111\stable-diffusion-webui\modules\scripts.py", line 243, in wrap_call
    res = func(*args, **kwargs)
  File "D:\GitHub\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-ar\scripts\sd-webui-ar.py", line 65, in ui
    self.read_aspect_ratios()
  File "D:\GitHub\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-ar\scripts\sd-webui-ar.py", line 41, in read_aspect_ratios
    lines = f.readlines()
  File "C:\Users\bruno\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 205: character maps to <undefined>

Error calling: D:\GitHub\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-ar\scripts\sd-webui-ar.py/ui
Traceback (most recent call last):
  File "D:\GitHub\AUTOMATIC1111\stable-diffusion-webui\modules\scripts.py", line 243, in wrap_call
    res = func(*args, **kwargs)
  File "D:\GitHub\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-ar\scripts\sd-webui-ar.py", line 65, in ui
    self.read_aspect_ratios()
  File "D:\GitHub\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-ar\scripts\sd-webui-ar.py", line 41, in read_aspect_ratios
    lines = f.readlines()
  File "C:\Users\bruno\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 205: character maps to <undefined>
```

python: 3.10.6  •  torch: 1.13.1+cu117  •  xformers: 0.0.16rc425  •  gradio: 3.16.2  •  commit: [226d840e]
(https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/226d840e84c5f306350b0681945989b86760e616)

most receent one

**Comment by alemelis** [comment]
@brunogcar I agree, those buttons should be on the official UI, but here we are...

Regarding the error, would you mind changing the two Unicode symbols in the `aspect_ratios.txt` file (phi and delta) to some ascii characters? It seems like it's an encoding/decoding error

**Comment by brunogcar** [comment]
> Regarding the error, would you mind changing the two Unicode symbols in the `aspect_ratios.txt` file (phi and delta) to some ascii characters? It seems like it's an encoding/decoding error

changed to p and d, no console errors and the aspect rations showed on ui, worked changind AR as expected, the red rectangle on readme
the custom part IMAX didn't show even with those changes, blue rectangle

btw win 11, my linux rig is out of commission atm to test

**Comment by brunogcar** [comment]
![AR](https://user-images.githubusercontent.com/53648/216725644-f52eb373-6532-48b2-aef9-7e7911242f15.png)

BTW the extension isnt like on your pics, its above scripts but in the middle of other extensions, no idea how to order that

ideally should be just bellow regular AT, but probably not possible to be placed above Restore faces,Tiling and Hires. fix, thats why should be on main ui, IMO

**Comment by alemelis** [comment]
Bit of a long shot, but what if you rename the extension folder so that it comes first in alphabetical order? Something like `AAA_sd-webui-ar`

Regarding the `IMAX` issue. Try to empty the `.txt` and have only a single line without comments. There may be differences between Linux and windows encoding which I'm not handling well

**Comment by brunogcar** [comment]
#2 https://github.com/alemelis/sd-webui-ar/pull/2/commits/81bb9c94280d7f1b74112fe1b3cf8853d8ecdd72 

fix console errors

> Regarding the `IMAX` issue. Try to empty the `.txt` and have only a single line without comments. There may be differences between Linux and windows encoding which I'm not handling well

https://github.com/alemelis/sd-webui-ar/blob/main/aspect_ratios.txt 

all lines are commented, so indeed  wasn't supposed to show, uncommented 3 lines to match your example


> Bit of a long shot, but what if you rename the extension folder so that it comes first in alphabetical order? Something like `AAA_sd-webui-ar`

yea, its alphabetically ordered on that module, same goes to Extension tab, way better on top, closer to where it should be

![AR](https://user-images.githubusercontent.com/53648/216779297-54ab04e9-f4cf-429a-87cd-a7bac220e2e4.png)

BTW, make a topic on A1111 Discussions, to let ppl know about that extension, probably will be added to https://raw.githubusercontent.com/wiki/AUTOMATIC1111/stable-diffusion-webui/Extensions-index.md and wiki that way

this is a quality of life addon, will be useful to many ppl, thanks

**Comment by gsgoldma** [comment]
Error calling: D:\stable-diffusion-webui\extensions\sd-webui-ar\scripts\sd-webui-ar.py/ui
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 243, in wrap_call
    res = func(*args, **kwargs)
  File "D:\stable-diffusion-webui\extensions\sd-webui-ar\scripts\sd-webui-ar.py", line 65, in ui
    self.read_aspect_ratios()
  File "D:\stable-diffusion-webui\extensions\sd-webui-ar\scripts\sd-webui-ar.py", line 41, in read_aspect_ratios
    lines = f.readlines()
  File "D:\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 205: character maps to <undefined>

Error calling: D:\stable-diffusion-webui\extensions\sd-webui-ar\scripts\sd-webui-ar.py/ui
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 243, in wrap_call
    res = func(*args, **kwargs)
  File "D:\stable-diffusion-webui\extensions\sd-webui-ar\scripts\sd-webui-ar.py", line 65, in ui
    self.read_aspect_ratios()
  File "D:\stable-diffusion-webui\extensions\sd-webui-ar\scripts\sd-webui-ar.py", line 41, in read_aspect_ratios
    lines = f.readlines()
  File "D:\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 205: character maps to <undefined>

got error as well

**Comment by alemelis** [comment]
@brunogcar @gsgoldma I've just merged @minemo fix, it should work fine now. Try to update the extension.

I'll think about a solution to move the extension on top of the list

**Comment by alemelis** [comment]
Closing this thanks to #2 

Feel free to reopen in case this is not solved
