### ISSUE TITLE
[Idea] Buttons disappeared? Handling for erroris in .txt files

### ISSUE THREAD

**Issue by VL4DST3R** [alemelis/sd-webui-ar#19]
~Is it just me or after the latest update the buttons are gone? Did a `reset --hard` as well, figuring it was my css or some other remnant file, but still no dice. No mentions of the extension or any errors in the console either.~

Edit: Turns out it was just me who forgot a `,` but this brings up another issue I've had a few times as i often add/remove presets- the fact that if one entry is wrong or an extra empty line is left somewhere, the entire extension fails to load.

Would it be possible to handle _more gracefully_ bad formatting via some sort of visible error, and ideally, have it be more permissive for things like new lines, which are helpful to quickly delimit groups of resolutions.

**Comment by alemelis** [comment]
Hi @VL4DST3R thanks for posting this issue/idea

In case of bad formatting you should already see some kind of error. For example say I have this line in `aspect_ratio.txt`
```
1:1 1.0 # square
```
where the `,` is missing. At startup you should see something like this

```
Model loaded in 7.8s (load weights from disk: 0.1s, create model: 1.0s, apply weights to model: 3.7s, apply half(): 2.9s).

Error calling: /stable-diffusion-webui/extensions/sd-webui-ar/scripts/sd-webui-ar.py/ui
Traceback (most recent call last):
  File "/stable-diffusion-webui/extensions/sd-webui-ar/scripts/sd-webui-ar.py", line 68, in parse_aspect_ratios_file
    label, value = line.strip().split(",")
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/stable-diffusion-webui/modules/scripts.py", line 243, in wrap_call
    res = func(*args, **kwargs)
  File "/stable-diffusion-webui/extensions/sd-webui-ar/scripts/sd-webui-ar.py", line 223, in ui
    self.read_aspect_ratios()
  File "/stable-diffusion-webui/extensions/sd-webui-ar/scripts/sd-webui-ar.py", line 193, in read_aspect_ratios
    ) = parse_aspect_ratios_file("aspect_ratios.txt")
  File "/stable-diffusion-webui/extensions/sd-webui-ar/scripts/sd-webui-ar.py", line 70, in parse_aspect_ratios_file
    gr.Error()
TypeError: Error.__init__() missing 1 required positional argument: 'message'

Error calling: /stable-diffusion-webui/extensions/sd-webui-ar/scripts/sd-webui-ar.py/ui
Traceback (most recent call last):
  File "/stable-diffusion-webui/extensions/sd-webui-ar/scripts/sd-webui-ar.py", line 68, in parse_aspect_ratios_file
    label, value = line.strip().split(",")
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/stable-diffusion-webui/modules/scripts.py", line 243, in wrap_call
    res = func(*args, **kwargs)
  File "/stable-diffusion-webui/extensions/sd-webui-ar/scripts/sd-webui-ar.py", line 223, in ui
    self.read_aspect_ratios()
  File "/stable-diffusion-webui/extensions/sd-webui-ar/scripts/sd-webui-ar.py", line 193, in read_aspect_ratios
    ) = parse_aspect_ratios_file("aspect_ratios.txt")
  File "/stable-diffusion-webui/extensions/sd-webui-ar/scripts/sd-webui-ar.py", line 70, in parse_aspect_ratios_file
    gr.Error()
TypeError: Error.__init__() missing 1 required positional argument: 'message'

[tag-editor] Settings has been read from config.json

Running on local URL:  http://127.0.0.1:7860
```
I agree I can make it prettier to explain the issue and also skip the badly formatted line

**Comment by alemelis** [comment]
done! let me know how it goes

**Comment by VL4DST3R** [comment]
I'll be honest i didn't know it reports an error, mostly given that i get a number of duplicate `unused kwarg parameters` at startup, this may have been lost through them and i failed to notice it.
