### ISSUE TITLE
Don't work with Automatic1111 forge version

### ISSUE THREAD

**Issue by Hakaan777** [alemelis/sd-webui-ar#25]
It seems that there's an issue with the Forge version of A1111, as no buttons are showing up

<img width="1132" alt="Capture d'écran 2024-08-14 052024" src="https://github.com/user-attachments/assets/aba09421-d6c0-4d0d-8a83-e97712ba1e2a">

**Comment by derpina-ai** [comment]
There are also errors in the log:

``   Error calling: I:\SD\forge\webui\extensions\sd-webui-ar\scripts\sd-webui-ar.py/ui
    Traceback (most recent call last):
      File "I:\SD\forge\webui\modules\scripts.py", line 545, in wrap_call
        return func(*args, **kwargs)
      File "I:\SD\forge\webui\extensions\sd-webui-ar\scripts\sd-webui-ar.py", line 244, in ui
        btns = [
      File "I:\SD\forge\webui\extensions\sd-webui-ar\scripts\sd-webui-ar.py", line 245, in <listcomp>
        ARButton(ar=ar, value=label)
      File "I:\SD\forge\webui\extensions\sd-webui-ar\scripts\sd-webui-ar.py", line 31, in __init__
        super().__init__(**kwargs)
      File "I:\SD\forge\webui\modules\ui_components.py", line 23, in __init__
        super().__init__(*args, elem_classes=["tool", *elem_classes], value=value, **kwargs)
      File "I:\SD\forge\webui\modules\gradio_extensions.py", line 146, in __repaired_init__
        original(self, *args, **fixed_kwargs)
      File "I:\SD\forge\system\python\lib\site-packages\gradio\component_meta.py", line 163, in wrapper
        return fn(self, **kwargs)
      File "I:\SD\forge\system\python\lib\site-packages\gradio\components\button.py", line 61, in __init__
        super().__init__(
      File "I:\SD\forge\webui\modules\gradio_extensions.py", line 36, in IOComponent_init
        res = original_IOComponent_init(self, *args, **kwargs)
      File "I:\SD\forge\system\python\lib\site-packages\gradio\component_meta.py", line 163, in wrapper
        return fn(self, **kwargs)
      File "I:\SD\forge\system\python\lib\site-packages\gradio\components\base.py", line 229, in __init__
        self.component_class_id = self.__class__.get_component_class_id()
      File "I:\SD\forge\system\python\lib\site-packages\gradio\components\base.py", line 118, in get_component_class_id
        module_path = sys.modules[module_name].__file__
    KeyError: 'sd-webui-ar.py'
``
